### ISSUE TITLE
MIMIC III reports not exist

### ISSUE THREAD

**Issue by LWHYC** [jbdel/vilmedic#10]

**Comment by jbdel** [comment]
Hello, 

if you are referring to the MIMIC-III reports for the summarization task, you can download it from this website
https://vilmedic.app/misc/bionlp23/sharedtask
I also invite you to participate to the task 

JB

**Comment by LWHYC** [comment]
Hello,

Thank you for your response, I am interested in participating in this task. I will download the MIMIC-III reports from the website you provided and give it a try.

Best,
Wenhui
