### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by bluch** [jbdel/vilmedic#16]
Installing VilMedic via `pip install vilmedic` is currently causing ResolutionImpossible errors.

> ERROR: Cannot install vilmedic==1.0.0, vilmedic==1.0.1, vilmedic==1.0.2, vilmedic==1.0.3, vilmedic==1.0.4, vilmedic==1.0.5, vilmedic==1.0.6, vilmedic==1.0.7, vilmedic==1.0.8, vilmedic==1.1.0, vilmedic==1.2.3, vilmedic==1.2.4, vilmedic==1.2.5, vilmedic==1.2.6, vilmedic==1.2.7, vilmedic==1.2.8, vilmedic==1.2.9 and vilmedic==1.3.0 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     vilmedic 1.3.0 depends on torchvision==0.9.1
>     vilmedic 1.2.9 depends on torchvision==0.9.1
>     vilmedic 1.2.8 depends on torchvision==0.9.1
>     vilmedic 1.2.7 depends on torchvision==0.9.1
>     vilmedic 1.2.6 depends on torchvision==0.9.1
>     vilmedic 1.2.5 depends on torchvision==0.9.1
>     vilmedic 1.2.4 depends on torchvision==0.9.1
>     vilmedic 1.2.3 depends on torchvision==0.9.1
>     vilmedic 1.1.0 depends on torchvision==0.9.1
>     vilmedic 1.0.8 depends on torchvision==0.9.1
>     vilmedic 1.0.7 depends on torchvision==0.9.1
>     vilmedic 1.0.6 depends on torchvision==0.9.1
>     vilmedic 1.0.5 depends on torchvision==0.9.1
>     vilmedic 1.0.4 depends on torchvision==0.9.1
>     vilmedic 1.0.3 depends on torchvision==0.9.1
>     vilmedic 1.0.2 depends on torchvision==0.9.1
>     vilmedic 1.0.1 depends on torchvision==0.9.1
>     vilmedic 1.0.0 depends on torchvision==0.9.1
> 

Tested on Python 3.10.12 (main, Jun  7 2023, 12:45:35) / Linux 77141cac7d20 5.15.107 x86_64 GNU/Linux.

**Comment by jbdel** [comment]
Vilmedic needs python 3.8
Last vilmedic version  (1.3.1) has been pushed on pypi.
