### ISSUE TITLE
Is the RadGraph model available on HuggingFace?

### ISSUE THREAD

**Issue by PabloMessina** [jbdel/vilmedic#17]
Hi, I was wondering if the RadGraph model is available on HuggingFace. I understand that the implementation is based on DYGIE++, but I wasn't able to find DYGIE++ in the HuggingFace library either. I'm also interested in replicating the training of the RadGraph model leveraging the released dataset, in combination with some additional tasks and supervision I have from other sources. I would like to fine-tune a BERT-based model from HuggingFace with the RadGraph dataset. Do you happen to have an implementation of a training script for RadGraph to use as an inspiration? 

Thanks in advance.

EDIT: I just asked a question on stackexchange that may help clarify what I'm trying to do: [Adapting a BERT-based model from HuggingFace for NER (named entity recognition) and RE (relation extraction)?](https://datascience.stackexchange.com/questions/123056/adapting-a-bert-based-model-from-huggingface-for-ner-named-entity-recognition)

**Comment by jbdel** [comment]
Unfortunately, its not available on HF
But its available as a python package
https://pypi.org/project/radgraph/0.0.8/
