### ISSUE TITLE
Does MVQA not using text information?

### ISSUE THREAD

**Issue by GanjinZero** [jbdel/vilmedic#5]
It seems MVQA inputs a image and do label classification? Question information is discarded?

**Comment by jbdel** [comment]
Hello,

Actually yes, the best performing model do not encode the questions.
MVQA task right now is a bit of a dummy task. Questions are like "what is the abnormality in the image" most of the time.
There are some recent paper that try to create better dataset: [https://openreview.net/pdf?id=uH_RlkvQMUs](https://openreview.net/pdf?id=uH_RlkvQMUs)
