### ISSUE TITLE
label_file dir in config.yml for mvqa/mvqa-imageclef

### ISSUE THREAD

**Issue by maloyan** [jbdel/vilmedic#7]
So I've downloaded `mvqa/mvqa-imageclef` from zoo and it automatically put everythin in .cache dir as it should

The problem is that the config.yml contains absolute path for 

```
label:
  label_file: /data/
```

So when I'm trying to load it, it's not looking in the .cache directory

**Comment by jbdel** [comment]
Hello,

Please excuse the delay in my response.  Thanks for pointing that out, there is indeed a mistake in the code.

Could you git pull the updated code. Everything should be working (the config will now point to the labels.tok in your cache dir).

JB
