### ISSUE TITLE
Can't find a vocabulary file at path

### ISSUE THREAD

**Issue by RParedesPalacios** [jbdel/vilmedic#8]
Hi, i am trying to run a report generation example with the rrg/baseline-padchest model

There are several problems downloading the model.pth that I just solved downloading from the google drive link and move that file to the .cache directory. However now it show up this error:

ValueError: Can't find a vocabulary file at path '/home/xxxx/.cache/vilmedic/zoo/models/rrg/baseline-padchest/vocab.tgt'. To load the vocabulary from a Google pretrained model use `tokenizer = BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)`

Where I could download that file?

Thanks

**Comment by jbdel** [comment]
Hello,

Indeed gdown package needed to be updated. Thats why you got issues to download the pth, and probably it didnt download the vocab.tgt.

Please do git pull to get the new setup.py, or simple upgrade gdown to v4.6.0

Delete your cache/vilmedic folder and re-do
`>>> model, processor = AutoModel.from_pretrained("rrg/baseline-padchest")
`
On my side, I get:
`Everything has been loaded successfully
`
Please tell me if everything works for you

**Comment by RParedesPalacios** [comment]
OK thanks I will try. I cloned the repository as it is just today. I guess that I should upgrade gdown. Anyway, I am using your HuggingFace Space just to try and see some results.
